blank_issues_enabled: false
contact_links:
  - name: Question / Pregunta
    url: https://github.com/GegesVTT/gg-wp/discussions
    about: For questions about how to use the module. / Para preguntas sobre cómo usar el módulo.
